TRANSPORTATION_MODES = [
    "Riding bus",
    "Riding bike",
    "Walking",
    "Riding mobility-on-demand shuttle",
    "Riding taxi",
    "Riding car",
    "Driving car",
]

SCENARIO_MAPPING = {
    "Mobility-on-demand shuttle: not available": "Scenario 1",
    "Mobility-on-demand shuttle: is Free when traveling within Tamaki-town": "Scenario 2",
    "Mobility-on-demand shuttle: costs 400 yen fixed when traveling within Tamaki-town": "Scenario 3",
    "Mobility-on-demand shuttle: costs 800 yen fixed when traveling within Tamaki-town": "Scenario 4",
}

ACTIVITY_COLORS = {
    "Sleep": "#1e3a5f",
    "Personal care": "#5b9bd5",
    "Meals": "#e8a838",
    "Housework": "#8fbc8f",
    "Caring or nursing": "#c9707d",
    "Child care": "#f4a6b8",
    "Shopping": "#d4a03c",
    "Watching TV": "#7b68ee",
    "Listening to the radio": "#9b8fcc",
    "Reading newspapers or magazines": "#6a5acd",
    "Rest and relaxation": "#87ceeb",
    "Learning": "#3cb371",
    "Self-education": "#2e8b57",
    "Training": "#228b22",
    "Hobbies and amusements": "#dda0dd",
    "Sports": "#ff6347",
    "Volunteer and social activities": "#20b2aa",
    "Social life": "#ff69b4",
    "Medical examination or treatment": "#cd5c5c",
    "Other activities": "#a9a9a9",
    "Arriving": "#d3d3d3",
    "Riding bus": "#ff8c00",
    "Riding bike": "#32cd32",
    "Walking": "#ffd700",
    "Riding mobility-on-demand shuttle": "#00ced1",
    "Riding taxi": "#ff4500",
    "Riding car": "#b22222",
    "Driving car": "#8b0000",
    "Unknown": "#808080",
}

SIM_TO_ACTIVITY_MAPPING = {
    "Sleep": "Sleep",
    "Personal care": "Personal care",
    "Meals": "Meals",
    "Housework": "Housework",
    "Caring or nursing": "Caring or nursing",
    "Child care": "Child care",
    "Shopping": "Shopping",
    "Watching TV": "Watching TV, listening to the radio, reading newspapers or magazines",
    "Listening to the radio": "Watching TV, listening to the radio, reading newspapers or magazines",
    "Reading newspapers or magazines": "Watching TV, listening to the radio, reading newspapers or magazines",
    "Rest and relaxation": "Rest and relaxation",
    "Learning": "Learning, self-education, and training (excluding schoolwork)",
    "Self-education": "Learning, self-education, and training (excluding schoolwork)",
    "Training": "Learning, self-education, and training (excluding schoolwork)",
    "Hobbies and amusements": "Hobbies and amusements",
    "Sports": "Sports",
    "Volunteer and social activities": "Volunteer and social activities",
    "Social life": "Social life",
    "Medical examination or treatment": "Medical examination or treatment",
    "Other activities": "Other activities",
    "Arriving": None,
}

COL_AGE = "Age"
COL_SEX = "Sex"
COL_HEALTH = "Usual state of health"
COL_SCENARIO = "Scenario"
COL_ACTIVITY = "Kind of activities"
COL_DAY_OF_WEEK = "Day of the week"
COL_VALIDATION = "Survey on Time Use and Leisure Activities 2021"
COL_SIMULATION = "Simulation"

QUESTIONNAIRE_A_COLS = [
    "Region_JP",
    "Region_EN",
    "Sample_EDs",
    "Sample_Households",
    "Sample_Persons_Leisure",
    "Sample_Persons_Time_Use",
    "Sample_Persons_Average_Time",
]

QUESTIONNAIRE_A_NUMERIC_COLS = [
    "Sample_EDs",
    "Sample_Households",
    "Sample_Persons_Leisure",
    "Sample_Persons_Time_Use",
    "Sample_Persons_Average_Time",
]

SE_RATIOS_ID_COLS = [
    "Day_of_week_JP",
    "Area_classification_JP",
    "Sex_JP",
    "Day_of_week_EN",
    "Area_classification_EN",
    "Sex_EN",
]

SE_RATIOS_ACTIVITIES = [
    "01_Sleep",
    "02_Personal care",
    "03_Meals",
    "04_Commuting to and from school or work",
    "05_Work",
    "06_Schoolwork",
    "07_Housework",
    "08_Caring or nursing",
    "09_Child care",
    "10_Shopping",
    "11_Moving (excluding commuting)",
    "12_Watching TV, listening to the radio, reading newspapers or magazines",
    "13_Rest and relaxation",
    "14_Learning, self-education, and training (excluding schoolwork)",
    "15_Hobbies and amusements",
    "16_Sports",
    "17_Volunteer and social activities",
    "18_Social life",
    "19_Medical examination or treatment",
    "20_Other activities",
    "R1_Primary activities(Regrouped)",
    "R2_Secondary activities(Regrouped)",
    "R3_Tertiary activities(Regrouped)",
]

AGENT_TRIPS_EXPORT_COLS = [
    "unique_simulation_id",
    "starting_time",
    "location",
    "next_loc",
    "start_x",
    "start_y",
    "dest_x",
    "dest_y",
]

ACTIVITIES = {
    "Sleep": {"duration": 60, "available_in": ["home", "lodging", "campground"]},
    "Personal care": {
        "duration": 20,
        "available_in": [
            "home",
            "lodging",
            "campground",
            "spa",
            "beauty_salon",
            "hair_care",
        ],
    },
    "Meals": {
        "duration": 20,
        "available_in": [
            "home",
            "establishment",
            "lodging",
            "campground",
            "bakery",
            "food",
            "restaurant",
            "convenience_store",
            "cafe",
            "meal_takeaway",
            "supermarket",
            "grocery_or_supermarket",
            "liquor_store",
        ],
    },
    "Housework": {
        "duration": 20,
        "available_in": ["home", "lodging", "campground", "laundry"],
    },
    "Caring or nursing": {"duration": 20, "available_in": ["home", "hospital"]},
    "Child care": {"duration": 20, "available_in": ["home", "park"]},
    "Shopping": {
        "duration": 20,
        "available_in": [
            "store",
            "atm",
            "clothing_store",
            "hardware_store",
            "electronics_store",
            "furniture_store",
            "home_goods_store",
            "book_store",
            "bicycle_store",
            "pet_store",
            "jewelry_store",
            "florist",
            "car_dealer",
        ],
    },
    "Watching TV": {
        "duration": 20,
        "available_in": ["home", "lodging", "campground", "book_store", "library"],
    },
    "Listening to the radio": {
        "duration": 20,
        "available_in": ["home", "lodging", "campground", "book_store", "library"],
    },
    "Reading newspapers or magazines": {
        "duration": 20,
        "available_in": ["home", "lodging", "campground", "book_store", "library"],
    },
    "Rest and relaxation": {
        "duration": 20,
        "available_in": [
            "home",
            "lodging",
            "campground",
            "park",
            "spa",
            "transit_station",
            "train_station",
            "parking",
            "point_of_interest",
            "locality",
            "sublocality",
            "political",
            "art_gallery",
            "museum",
            "tourist_attraction",
        ],
    },
    "Learning": {"duration": 20, "available_in": ["home", "book_store", "library"]},
    "Self-education": {
        "duration": 20,
        "available_in": ["home", "book_store", "library"],
    },
    "Training": {"duration": 20, "available_in": ["home", "book_store", "library"]},
    "Hobbies and amusements": {
        "duration": 20,
        "available_in": ["home", "lodging", "campground"],
    },
    "Sports": {"duration": 20, "available_in": ["campground", "gym", "park"]},
    "Volunteer and social activities": {
        "duration": 20,
        "available_in": ["place_of_worship", "local_government_office", "city_hall"],
    },
    "Social life": {
        "duration": 20,
        "available_in": [
            "establishment",
            "lodging",
            "campground",
            "bakery",
            "food",
            "restaurant",
            "convenience_store",
            "cafe",
            "meal_takeaway",
            "supermarket",
            "grocery_or_supermarket",
            "liquor_store",
            "gym",
            "park",
            "store",
            "atm",
            "clothing_store",
            "hardware_store",
            "electronics_store",
            "furniture_store",
            "home_goods_store",
            "book_store",
            "bicycle_store",
            "pet_store",
            "jewelry_store",
            "florist",
            "car_dealer",
            "funeral_home",
            "spa",
            "beauty_salon",
            "city_hall",
            "art_gallery",
            "museum",
            "tourist_attraction",
        ],
    },
    "Medical examination or treatment": {
        "duration": 20,
        "available_in": [
            "hospital",
            "doctor",
            "dentist",
            "pharmacy",
            "drugstore",
            "health",
        ],
    },
    "Other activities": {
        "duration": 20,
        "available_in": [
            "place_of_worship",
            "cemetery",
            "local_government_office",
            "city_hall",
            "bank",
            "accounting",
            "lawyer",
            "post_office",
            "police",
            "laundry",
            "travel_agency",
            "real_estate_agency",
            "insurance_agency",
            "electrician",
            "painter",
            "locksmith",
            "car_repair",
            "moving_company",
            "general_contractor",
            "roofing_contractor",
        ],
    },
    "Arriving": {"duration": 5, "available_in": None},
    "Riding bus": {"duration": 5, "available_in": None},
    "Riding bike": {"duration": 5, "available_in": None},
    "Walking": {"duration": 5, "available_in": None},
    "Riding mobility-on-demand shuttle": {"duration": 5, "available_in": None},
    "Riding taxi": {"duration": 5, "available_in": None},
    "Riding car": {"duration": 5, "available_in": None},
    "Driving car": {"duration": 5, "available_in": None},
}

TRAVEL_MODES = {
    "Riding bus": {"speed": 45},
    "Riding bike": {"speed": 20},
    "Walking": {"speed": 10},
    "Riding mobility-on-demand shuttle": {"speed": 55},
    "Riding taxi": {"speed": 60},
    "Riding car": {"speed": 60},
    "Driving car": {"speed": 60},
}
